services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hhplus-app
    container_name: hhplus-app
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=application
      - SPRING_DATASOURCE_PASSWORD=application
      - SPRING_REDIS_HOST=redis-master
      - SPRING_REDIS_PORT=6379
    networks:
      eknetwork:

networks:
  eknetwork: